#!/usr/bin/env bash

# Function to display subdomain information
print_info() {
    local domain="$1"
    local subdomain="$2"

    local dns_info
    dns_info=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1)

    local subdomain_name
    subdomain_name=$(echo "$dns_info" | awk '{print $1}')
    local record_type
    record_type=$(echo "$dns_info" | awk '{print $4}')
    local destination
    destination=$(echo "$dns_info" | awk '{print $5}')

    echo "The subdomain $subdomain_name is a $record_type record and points to $destination"
}

# Check the number of arguments provided
if [ "$#" -eq 2 ]; then
    print_info "$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_info "$1" "$subdomain"
    done
fi
