#!/usr/bin/env bash
# Install nginx
# Nginx should be listening on port 80

# Update package lists to get the latest package information
sudo apt-get update

# Install Nginx with the '-y' option to automatically answer 'yes' to prompts
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file with "Hello, world!" content and place it in the default web directory
echo "Hello world!" | sudo tee /var/www/html/index.html

# Restart the Nginx service to apply the changes
sudo service nginx restart
