#!/usr/bin/env bash
# Configure an Nginx server to perform a redirect

# Update package lists to get the latest package information
sudo apt-get -y update

# Install Nginx with the '-y' option to automatically answer 'yes' to prompts
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall for Nginx
sudo ufw allow 'Nginx HTTP'

# Create a simple HTML file with "Hello World" content and place it in the default web directory
echo "Hello World" | sudo tee /var/www/html/index.html

# Use 'sed' to add a rewrite rule in the Nginx configuration
# This rule redirects "/redirect_me" to "https://www.youtube.com/"
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Restart the Nginx service to apply the changes
sudo service nginx restart
