#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package lists to get the latest package information
sudo apt-get -y update

# Install Nginx with the '-y' option to automatically answer 'yes' to prompts
sudo apt-get -y install nginx

# Create a simple HTML file with "Hello World!" content and place it in the default web directory
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404 error page with the message "Ceci n'est pas une page"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Use 'sed' to add error handling for 404 errors in the Nginx configuration
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }' /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start
