#!/usr/bin/env bash
# Configure the Nginx server to listen on port 80

# Remove the default Nginx server configuration file
sudo rm /etc/nginx/sites-enabled/default
# Create a symbolic link to the default Nginx configuration for port 80
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart the Nginx service to apply the configuration changes
sudo service nginx restart
