#!/usr/bin/env bash
# This script displays the required information from the /etc/passwd file.

while IFS=: read -r username _ userid _ homedir _; do
  echo "$username:$userid:$homedir"
done < /etc/passwd
