#!/usr/bin/env bash
# This script displays different messages for each loop iteration.

count=1
while [ $count -le 10 ]; do
  case $count in
    4)
      echo "bad luck"
      ;;
    8)
      echo "good luck"
      ;;
    *)
      echo "Best School"
      ;;
  esac
  ((count++))
done
