#!/usr/bin/env bash
# Change the Nginx user from 'www-data' to 'nginx' in the Nginx configuration file.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Modify the default Nginx site configuration to listen on port 8080 instead of port 80.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Set the permissions for the Nginx configuration file to 644 (readable by owner and group).
chmod 644 /etc/nginx/nginx.conf

# Terminate any running Apache processes (assuming you're switching from Apache to Nginx).
pkill apache2

# Start the Nginx service with the 'nginx' user.
sudo -u nginx service nginx start
