#!/usr/bin/env bash
# Terminate any running Apache processes and restart Nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx: /etc/nginx/nginx.conf && chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart