#!/usr/bin/env bash
# Creates a new 4096 byte RSA key pair named school
ssh-keygen -t rsa -b 4096 -N betty -f school

echo "RSA key pair generated:"
echo "Private key: $key_name"
echo "Public key: ${key_name}.pub"