#!/usr/bin/env bash
#SSH client configuration file

Host *
    IdentifyFile ~/.ssh/school
    PasswordAuthentication no
    SendEnv LANG LC_*
    PreferredAuthentications publickey
    HashKnownHosts yes
    GSSAPIDelegateCredentials no
    GSSAPIAuthentication yes